# Generated by Django 4.2.4 on 2023-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='')),
                ('mail', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=10)),
                ('phnumber', models.IntegerField(default='')),
            ],
        ),
    ]
